[tasks.fmt]
description = "Run all fmt:* tasks"
depends = "fmt:*"

[tasks.lint]
description = "Run all lint:* tasks"
depends = "lint:*"

[tasks.test]
description = "Run all test:* tasks"
depends = "test:*"

[tasks.ci]
description = "Run all ci:* tasks"
depends = "ci:*"
